### ISSUE TITLE
AttributeError: '_CaseInsensitiveDictionary' object has no attribute 'copy'

### ISSUE THREAD

**Issue by botzill** [scrapedia/scrapy-pipelines#29]
Having this issue:

Python 3.7,
Scrapy 1.7.3

```
Traceback (most recent call last):
  File "/Users/mac/.virtualenvs/tags_crawler/lib/python3.7/site-packages/scrapy/crawler.py", line 88, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
AttributeError: '_CaseInsensitiveDictionary' object has no attribute 'copy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/.virtualenvs/tags_crawler/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/Users/mac/.virtualenvs/tags_crawler/lib/python3.7/site-packages/scrapy_pipelines/pipelines/mongo.py", line 160, in close_spider
    yield self.mongo.disconnect()
AttributeError: 'NoneType' object has no attribute 'disconnect'
2019-09-20 22:59:52 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method CoreStats.spider_closed of <scrapy.extensions.corestats.CoreStats object at 0x11292ccf8>>
Traceback (most recent call last):
  File "/Users/mac/.virtualenvs/tags_crawler/lib/python3.7/site-packages/scrapy/crawler.py", line 88, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
AttributeError: '_CaseInsensitiveDictionary' object has no attribute 'copy'
```

I have a `CrawlerSpider` and even if the code is:

```
    def start_requests(self):
        return []
        # yield scrapy.Request(self.input_data[0], callback=self.parse)
```

Stil I have these issues.

Any idea?

**Comment by grammy-jiang** [comment]
I think this issue is more about creating a connection with `MongoDB`.

From the error message, we know `self.mongo` is None, which means it is not successfully created in `MongoPipeline.open_spider`.

My suggestion is that you can have a look at `MongoPipeline.open_spider` to see if anything configuration is missing.
